### PR TITLE
Update Sandstorm API advice

### LINKED ISSUE #5: Cron advice is out of date
https://github.com/sandstorm-io/php-app-to-package-for-sandstorm/blob/master/index.php#L143 just says that Cron jobs would be tough for now. Ideally we should link to the docs for the feature, as a PHP app is even currently using that API.

### PR DESCRIPTION
**Pull request by ocdtrekkie**
Fixes #5, and also recommends Ian's powerbox-http-proxy over a as-far-as-I-know never-published tool by Jason.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
@zenhack Probably the only change here particularly warranting your review, but I don't believe we have a better place to refer to for Cron docs. I might open an issue in the main repo for that.

**Comment by zenhack** [comment]
I don't love just pointing people to powerbox-http-proxy and saying "use this for http;" it's meant to make porting apps that expect ambient HTTP access easier, but if you're writing a greenfield app it will often be a better UX if you do the powerbox dance yourself in response to the thing the user tried to do. I'd like it if the docs actually discussed the differences.

**Comment by ocdtrekkie** [comment]
I agree in theory, but in practice, especially for a stack like PHP, we're not offering... much of anything... to get people there.

The next test app I am intending to put together is Go, and I am hoping to offer a better recommendation there.

**Comment by zenhack** [comment]
Yeah, it might be nice to port the server-side parts of https://github.com/zenhack/hello-sandstorm-oauth to PHP (which maybe we should transfer to this org?)

I'm ok with merging this for now.

**Comment by ocdtrekkie** [comment]
I am +1 on bringing some repos in-house to the main org, was thinking about a few from the sandstormports org too, but I figured I'd run that by you and Kenton at some point.

And yeah, a better PHP solution might be nice but I also don't know how much greenfield PHP dev for Sandstorm we should expect (other than my own...)

**Comment by zenhack** [comment]
I went ahead and moved that repo to the sandstorm-io org.

**Pull request merged**
